spring.application.name=Library

spring.datasource.url=jdbc:mysql://localhost:3306/Library
spring.datasource.username=root
spring.datasource.password=Haniny@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
